### ISSUE TITLE
Separate compilers and tests in dependencies?

### ISSUE THREAD

**Issue by matthew-dean** [jescalan/accord#191]
My use case: I'd like to keep my app up-to-date with accord support as much as possible. In other words: support the compilers that accord supports.

To do that, I'd like to, of course, install all said compilers. The hack solution I have right now is to run `npm install` in the accord directory, to install the dev dependencies. However, I notice that this also installs all of the modules in that list that are used for running tests.

Would it be possible to move all of the non-compiler modules into `optionalDependencies` so that I could exclude them? Or would you have an alternate suggestion for how to easily keep supported compilers in sync with accord?

**Comment by davej** [comment]
That is not what `optionalDependencies` are for and it would cause the test modules to be installed by anyone doing a standard `npm install accord`.

Your best bet is to create a script which maps through `require('accord').all()` and installs the relevant engines. Keep in mind that for some modules you may need to look for `supportedEngines` on the prototype instead of just using the key (with babel for example).

**Comment by jescalan** [comment]
No, they are not optional, they are required for those using this package. Unfortunately I can't flex the package around needs for your app.

As far as solving the issue, I would read the `lib/adapters` directory and grab all the names from there. Now not every adapter name is 1:1 with it's engine's name, so you'd need one more transform. You have two options here:

1. Run them through [this function](https://github.com/jescalan/accord/blob/master/lib/index.coffee#L30). I would accept a pull request that exports that function if you want it to be public.
2. Get the `supportedEngines` property, as @davej suggested above, if it exists, and use that instead of the file name.

Whatever path you take, then take the resulting array, format it as a string, and run `npm install`.

**Comment by matthew-dean** [comment]
> That is not what optionalDependencies are for and it would cause the test modules to be installed by anyone doing a standard npm install accord.

Yeah, that was my best guess but I'm not completely familiar with `npm install` options.

> Your best bet is to create a script which maps through require('accord').all() and installs the relevant engines. 

Interesting idea.

**Comment by matthew-dean** [comment]
@jescalan Thanks for the additional feedback. When more than one engine is supported, does accord order them by which one is preferred? Obviously I would only need to install one of them, so I'm just wondering if you already rank / prefer them.

**Comment by jescalan** [comment]
First one in the array is preferred, but if there are two supported engines they will be equal in functionality, so it shouldn't matter 😁

**Comment by matthew-dean** [comment]
Okay thanks. If exposing a method for installing these engines is not a priority, I think you can safely close this.

**Comment by matthew-dean** [comment]
With #192 I got this working in no time, thanks! Would love to see that merged. ^_^
