### ISSUE TITLE
Replacing fobject dependency with a non-GPL dependency

### ISSUE THREAD

**Issue by pgilad** [jescalan/accord#208]
Hi, as much as I would like to support open source software, GPL license causes a major headache to anyone that doesn't want to consult lawyers and/or understand if their particular use-case causes infection of the GPL license.

I recommend either switching to an earlier version of `fobject` (from before GPL), finding an `fobject` alternative, or forking `fobject` from before GPL and improving that.

I can help with any of the above, let me know if this can be considered.

**Comment by jescalan** [comment]
Hey there @pgilad! I'd like to wait for a response from @slang800 on [your latest comment here](https://github.com/slang800/fobject/commit/9dbe451bbf43f678e265a1033defe7a4f5a8f101#commitcomment-18086973), which was made less than an hour ago, before moving forward with this.

If we have come to a place where there are irreconcilable differences, I will side with you here, because I hate licenses just want to make this software freely available.

**Comment by slang800** [comment]
> GPL license causes a major headache to anyone that doesn't want to consult lawyers and/or understand if their particular use-case causes infection of the GPL license.

If you don't want to understand the GPL, then you probably shouldn't be using git, since that's GPL- licensed too.

I wrote a lengthy reply [in the fobject commit log](https://github.com/slang800/fobject/commit/9dbe451bbf43f678e265a1033defe7a4f5a8f101#commitcomment-18087512), but I suppose I should reply here too, since this is the [2nd time we've had someone bring this up](https://github.com/jescalan/accord/issues/180)...

This fear of "infection" comes from a fundamental lack of understanding how the GPL (and licensing in general) works. Even if I wanted to, I couldn't assert ownership or enforce licensing terms on projects I don't own. The GPL only applies to projects that decide to use it - in this case fobject and _not_ accord. At worst, you could put your project into a state of non-compliance, if you (for example) forked fobject, made changes, used it in a closed-source product, and then didn't release the source code changes back to the public. But even then, the GPL **cannot** "infect" another codebase, make you give up your source code, or force you to change licenses.

In the case of accord, fobject isn't even being forked, it's merely being required as part of an "aggregate", which doesn't cause the terms of the GPL to apply to other works in that aggregate. This means you could take the full source code of roots, package it up as a product, sell it to people without providing the source code, and continue to develop it as a closed-source project, so long as you don't make modifications to fobject.

**Comment by pgilad** [comment]
Thanks for the lengthy response. I'm not saying GPL is a harsh or invalid license, but saying once you have to consider and think about what you do with a project (directly or indirectly), and you have an easy alternative (which does not cause the same complications), I choose the easy alternative.

**Comment by jescalan** [comment]
Thanks for the clear explanation @slang800. I don't see an issue here. If you are packaging accord into a closed source project and modifying fobject, you will also need to modify accord, which means you'll need a fork anyway. If you have improvements to fobject, surely @slang800 would be happy to take a look at them through a PR and make them happen.

There is no license in existence that you don't need to read and consider the terms of. It doesn't seem like the GPL license is going to hold you back on whatever you are working on, so I'm going to close this out.
