### ISSUE TITLE
Acknowledge JSTransformers in README

### ISSUE THREAD

**Issue by calebeby** [jescalan/accord#262]
Hi guys,

I think the README should be updated to address [JSTransformers](https://github.com/jstransformers/jstransformer), now that transformers are depricated.

**Comment by jescalan** [comment]
Sure, what would you recommend adding? Care to take a stab at a PR?

**Comment by calebeby** [comment]
I can make a PR, but I would like you to expand on "we designed accord to provide a more maintainable code base and way of writing adapters". I understand that you use promises for everything, but so do JSTransformers, (well, all transformers implement `renderAsync` and most implement `render` (sync).

Thanks

**Comment by jescalan** [comment]
Jstransformers, I think, was not complete or good when accord was initially built. But even now it doesn't have support for a lot of the features accord has. It doesn't deal with source maps at all, doesn't expose the raw compiler engine, doesn't keep track of package names or file extensions for each language, doesn't support multiple versions of an engine even through breaking changes, etc. These are some very important features that are utilized heavily by a lot of accord users.

**Comment by calebeby** [comment]
OK. I'll see if I can get a pull request in this weekend.

**Comment by calebeby** [comment]
I'm going to remove the line about promises, because both consolidate and jstransformers can return promises for all transformers/adapters/engines.

**Comment by calebeby** [comment]
I am rephrasing your above paragraph in the PR.
The PR (WIP) is #263

I have a few questions:

How does accord do the following better/differently from JSTransformers?

- "expose the raw compiler engine" I don't really get what you mean by this.
- "keep track of package names... for each language"? I don't get this one. In JSTransformer, each transformer imports the corresponding preprocessor.
- "keep track of... file extensions for each language" JSTransformers expose `inputformats`, `outputformat`, and sometimes `name`. Example: https://github.com/jstransformers/jstransformer-stylus/blob/master/index.js#L9
- "support multiple versions of an engine even through breaking changes" I think it's a neat idea that accord has a different file to support different versions of transpilers, but JSTransformers achieves this by having each adapter/transformer as a separate npm module, so you can install whichever version you want.

**Comment by jescalan** [comment]
- Both libraries wrap the underlying compiler. Accord will expose the wrapped compiler if you need to work with it for any reason.
- From an accord adapter, you can pull the exact name of the node module that can be installed to support the adapter with a single property. This way you can look through the package.json to detect whether a given processor is installed and ready to roll. Perhaps jstransformers has this, but I didn't see it listed!
- Didn't know about input and output formats, but that looks like a feature match. Does every jstransformer in existence support these? As a consequence of having all the transformers in core, accord can guarantee this. If jstransformers threw an error message when missing these properties it could guarantee their existence in plugins -- does it do this?
- The difference here is that you will have a huge mess on your hands if a single module goes through like 3 or 4 breaking changes. You have `jstransformer-stylus`, for example. Now, stylus has a breaking change to the API, so you make `jstransformer-stylus2`? Then uninstall your existing one and reinstall a new one? It would be much cleaner to use major versions on each transformer to adapt along with the wrapped processor's api. Maybe this is what's done already? With accord, there is no version changing needed at all, you can use the same version for an old version of sass as the current version, since it goes to find the package version and matches it with an internal accord adapter on initialization, so it's quite smooth. But I'd be ok with the major version bump on the transformer method -- it wouldn't be quite as smooth, but it would get the job done.

In general, jstransformers looks like it has come a very long way since accord was built a number of years ago. If it was able to match all the features, I would happily deprecate accord -- one less thing for me to maintain 😁 . It seems to me like the big one at this point is source maps?

**Comment by calebeby** [comment]
Thanks for clarifying. The PR is ready.
