### ISSUE TITLE
accord.load customPath, what does it do?

### ISSUE THREAD

**Issue by Munter** [jescalan/accord#89]
I don't get what the custom path in the load function is supposed to do.

The only reference I can find of usage is in this test: https://github.com/jenius/accord/blob/master/test/test.coffee#L27

But that test is completely broken. The engine of the returned adapter is the node `path` module. I am pretty sure that is not what was intended

**Comment by Munter** [comment]
Also, the README says it's an object. Not how it's used, just to be careful. Is this some left over from previous iterations?

**Comment by slang800** [comment]
If you need to use a particular installation of an engine (rather than the one that `require` resolves to automatically) then you pass the path to the root of the module as `customPath`. And I think it's still used.

I added some docs for it [here](https://github.com/slang800/accord/commit/dd17e56197680b964ae973fa005cfcf150b3e82b), along with renaming it to `enginePath` so it makes a little more sense... but they never got pulled in.

**Comment by Munter** [comment]
What I gather from the code and the test this is not the behavior it has. It seems to currently just pop the name of the last directory in your custom path and try to load that using `require`.

And this is how the test I linked to has an engine that is equal to `require('path')`, which I assume is not intended

**Comment by slang800** [comment]
Yeah, I'm not sure what that test is supposed to be doing... passing an incorrect 

As for the code that pops off the name of the last directory in the custom path - that's probably just for getting the engine path from the name, when we don't have a customPath. You're talking about https://github.com/jenius/accord/blob/eb352ddffe95cc67c7b59224c8ef1d3e27d4dfbc/lib/adapter_base.coffee#L172, right?

The part that actually requires the engine when we have a customPath is here: https://github.com/jenius/accord/blob/eb352ddffe95cc67c7b59224c8ef1d3e27d4dfbc/lib/adapter_base.coffee#L155

**Comment by jenius** [comment]
Yeah honestly I'm not sure what the story is with that test. I don't think I wrote it, but should definitely fix it. Thanks for the heads up!

**Comment by slang800** [comment]
@jenius: yeah, you didn't write it - it was introduced in 07b3a09ce3efe647d55bd09018243905224aea7a. Maybe @joshrowley remembers what it was for?

**Comment by joshrowley** [comment]
Here's the associated [PR](https://github.com/jenius/accord/pull/24). It was for a use case that's no longer needed (at least for me, it was for a specific use case in roots-cms which is no longer an active project).

The reasoning was I had a project called roots-cms with an associated dependency roots-cms-client and both required coffeescript. However npm installs coffeescript at the top level for roots-cms, and since roots-cms-client shared the dependency, it didn't install coffeescript in roots-cms-client. Node is able to do this because any time coffeescript is required in roots-cms-client, if it doesn't find it in the most immediate `node_modules` directory, it looks up the directory tree to see if it's available in `node_modules` further up the dependency tree.

That's the story behind the test, it's just testing that if I pass in a custom path that doesn't immediately have the required module, accord will then look up the tree and find it in a higher up dep.

Feel free to get rid of the test, but I think accord using the same require logic as node should stay.
